version: '3.7'

services:
  vue-app:
    container_name: adempiere-vue
    build: .
    # image: erpya/adempiere-vue
    stdin_open: true
    tty: true
    environment:
      - API_URL=https://api.erpya.com
    ports:
      - 80:80
